apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  selector:
    matchLabels:
      run: celery-beat
  replicas: 1
  template:
    metadata:
      labels:
        run: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: sneyd321/celery-beat
  
      imagePullSecrets:
        - name: key