apiVersion: apps/v1
kind: Deployment
metadata:
  name: registrar-service
spec:
  selector:
    matchLabels:
      run: registrar-service
  replicas: 1
  template:
    metadata:
      labels:
        run: registrar-service
    spec:
      containers:
      - name: registrar-service
        image: sneyd321/registrar-service
        ports:
        - containerPort: 8089

  
        
      imagePullSecrets:
        - name: key